language: common-lisp
sudo: false

addons:
  apt:
    packages:
      - libc6-i386
      - clisp
      - openjdk-7-jre

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl
    - LISP=cmucl
    - LISP=alisp

os:
  - linux
  - osx

matrix:
  allow_failures:
    - env: LISP=clisp
    - env: LISP=abcl
    - env: LISP=ecl
    - env: LISP=cmucl
    - env: LISP=alisp

before_install:
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew update
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && source ./macports-ci install
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && source ./macports-ci ccache
      
install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - ros install guicho271828/trivial-package-manager
  - ros install guicho271828/cl-sat

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp
    - $HOME/.macports-ci-ccache

script:
  - ./testscr.ros
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && source macports-ci ccache --save
